../../bin/analyze contrived_water  EV

#  General System and Force Field Information [G]
#  Force Field Parameters for Interactions [P]
#  Total Potential Energy and its Components [E]
#  Energy Breakdown over Each of the Atoms [A]
#  List of the Large Individual Interactions [L]
#  Details for All Individual Interactions [D]
#  Electrostatic Moments and Principle Axes [M]
#  Internal Virial, dE/dV Values & Pressure [V]
#  Connectivity Lists for Each of the Atoms [C]
