../../bin/analyze contrived_water epm -1 6

# General System and Force Field Information [G]
# Force Field Parameters for Interactions [P]
# Total Potential Energy and its Components [E]
# Energy Breakdown over Each of the Atoms [A]
# List of the Large Individual Interactions [L]
# Details for All Individual Interactions [D]
# Electrostatic, Inertial & Virial Properties [M]
# Connectivity Lists for Each of the Atoms [C]
